//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class ActionsNotification
    {
    	
    
        public ActionsNotification()
        {
            this.Action_SecurityRole_MailTemplate = new HashSet<Action_SecurityRole_MailTemplate>();
            this.Action_Step_MailTemplate = new HashSet<Action_Step_MailTemplate>();
        }
    
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public string Name { get; set; }
    
        [DataMember] public Nullable<System.Guid> DefaultMailTemplateId { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        public virtual ICollection<Action_SecurityRole_MailTemplate> Action_SecurityRole_MailTemplate { get; set; }
        public virtual ICollection<Action_Step_MailTemplate> Action_Step_MailTemplate { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
