//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Condtion
    {
    	
    
        public Condtion()
        {
            this.FlowLogic_Condtion = new HashSet<FlowLogic_Condtion>();
        }
    
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public string Name { get; set; }
    
        [DataMember] public System.Guid StepRequiredItemId { get; set; }
    
        [DataMember] public System.Guid MatchingCritriaId { get; set; }
    
        [DataMember] public Nullable<double> MatchingValue_Number { get; set; }
    
        [DataMember] public Nullable<System.Guid> MatchingValue_Lookup { get; set; }
    
        [DataMember] public string MatchingValue_Text { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        public virtual lkup_MatchingCritria lkup_MatchingCritria { get; set; }
        public virtual StepRequiredItem StepRequiredItem { get; set; }
        public virtual ICollection<FlowLogic_Condtion> FlowLogic_Condtion { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
