//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class lkup_StepType
    {
    	
    
        public lkup_StepType()
        {
            this.Step = new HashSet<Step>();
            this.StepType_Status = new HashSet<StepType_Status>();
        }
    
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public string Name { get; set; }
    
        [DataMember] public string Description { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        [DataMember] public Nullable<System.Guid> InProgressStatusId { get; set; }
    
        [DataMember] public Nullable<System.Guid> NotStartedStatusId { get; set; }
    
        public virtual ICollection<Step> Step { get; set; }
        public virtual ICollection<StepType_Status> StepType_Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
