//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class lkup_SecurityRole
    {
    	
    
        public lkup_SecurityRole()
        {
            this.SecurityMatrix = new HashSet<SecurityMatrix>();
            this.Step = new HashSet<Step>();
        }
    
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public string Name { get; set; }
    
        [DataMember] public Nullable<bool> VisibleInSM { get; set; }
    
        [DataMember] public Nullable<System.Guid> DefaultUserId { get; set; }
    
        [DataMember] public Nullable<System.Guid> DefautOwnerRoleId { get; set; }
    
        [DataMember] public Nullable<bool> StakeHolder { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        public virtual ICollection<SecurityMatrix> SecurityMatrix { get; set; }
        public virtual ICollection<Step> Step { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
