//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StepPointWFEntities : DbContext
    {
        public StepPointWFEntities()
            : base("name=StepPointWFEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action_SecurityRole_MailTemplate> Action_SecurityRole_MailTemplate { get; set; }
        public virtual DbSet<Action_Step_MailTemplate> Action_Step_MailTemplate { get; set; }
        public virtual DbSet<ActionsNotification> ActionsNotification { get; set; }
        public virtual DbSet<Condtion> Condtion { get; set; }
        public virtual DbSet<CustomFieldType> CustomFieldType { get; set; }
        public virtual DbSet<DelegationScope> DelegationScope { get; set; }
        public virtual DbSet<FlowLogic> FlowLogic { get; set; }
        public virtual DbSet<FlowLogic_Condtion> FlowLogic_Condtion { get; set; }
        public virtual DbSet<FlowLogicRequiredItem> FlowLogicRequiredItem { get; set; }
        public virtual DbSet<ItemSubmittionHistory> ItemSubmittionHistory { get; set; }
        public virtual DbSet<lkup_DelegationStatus> lkup_DelegationStatus { get; set; }
        public virtual DbSet<lkup_Group> lkup_Group { get; set; }
        public virtual DbSet<lkup_JobTitle> lkup_JobTitle { get; set; }
        public virtual DbSet<lkup_Language> lkup_Language { get; set; }
        public virtual DbSet<lkup_LookupList> lkup_LookupList { get; set; }
        public virtual DbSet<lkup_LookUpListValue> lkup_LookUpListValue { get; set; }
        public virtual DbSet<lkup_MailTemplate> lkup_MailTemplate { get; set; }
        public virtual DbSet<lkup_MatchingCritria> lkup_MatchingCritria { get; set; }
        public virtual DbSet<lkup_Path> lkup_Path { get; set; }
        public virtual DbSet<lkup_Phase> lkup_Phase { get; set; }
        public virtual DbSet<lkup_RequiredItemType> lkup_RequiredItemType { get; set; }
        public virtual DbSet<lkup_SecurityRole> lkup_SecurityRole { get; set; }
        public virtual DbSet<lkup_Status> lkup_Status { get; set; }
        public virtual DbSet<lkup_StepType> lkup_StepType { get; set; }
        public virtual DbSet<lkup_SubmittionStatus> lkup_SubmittionStatus { get; set; }
        public virtual DbSet<lkup_TimeOutStatus> lkup_TimeOutStatus { get; set; }
        public virtual DbSet<Object_StepRequiredItem> Object_StepRequiredItem { get; set; }
        public virtual DbSet<ObjectInstanceData> ObjectInstanceData { get; set; }
        public virtual DbSet<ObjectInstanceData_CurrentSteps> ObjectInstanceData_CurrentSteps { get; set; }
        public virtual DbSet<ObjectStepHistory> ObjectStepHistory { get; set; }
        public virtual DbSet<ObjectTypeWorkflow> ObjectTypeWorkflow { get; set; }
        public virtual DbSet<SecurityMatrix> SecurityMatrix { get; set; }
        public virtual DbSet<Step> Step { get; set; }
        public virtual DbSet<Step_StepRequiredItem> Step_StepRequiredItem { get; set; }
        public virtual DbSet<StepCompletedItemHistory> StepCompletedItemHistory { get; set; }
        public virtual DbSet<StepRequiredItem> StepRequiredItem { get; set; }
        public virtual DbSet<StepType_Status> StepType_Status { get; set; }
        public virtual DbSet<Workflow> Workflow { get; set; }
        public virtual DbSet<Workflow_Attachment> Workflow_Attachment { get; set; }
        public virtual DbSet<WorkflowComment> WorkflowComment { get; set; }
        public virtual DbSet<WorkflowDelegation> WorkflowDelegation { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual ObjectResult<ActionsNotification_GetById_Result> ActionsNotification_GetById(Nullable<System.Guid> id, Nullable<System.Guid> securityRoleId, Nullable<System.Guid> stepID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var securityRoleIdParameter = securityRoleId.HasValue ?
                new ObjectParameter("SecurityRoleId", securityRoleId) :
                new ObjectParameter("SecurityRoleId", typeof(System.Guid));
    
            var stepIDParameter = stepID.HasValue ?
                new ObjectParameter("StepID", stepID) :
                new ObjectParameter("StepID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActionsNotification_GetById_Result>("ActionsNotification_GetById", idParameter, securityRoleIdParameter, stepIDParameter);
        }
    
        public virtual ObjectResult<Attachment_GetById_Result> Attachment_GetById(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Attachment_GetById_Result>("Attachment_GetById", idParameter);
        }
    
        public virtual ObjectResult<Condtion_GetByStepRequiredItemId_Result> Condtion_GetByStepRequiredItemId(Nullable<System.Guid> stepRequiredItemId)
        {
            var stepRequiredItemIdParameter = stepRequiredItemId.HasValue ?
                new ObjectParameter("StepRequiredItemId", stepRequiredItemId) :
                new ObjectParameter("StepRequiredItemId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Condtion_GetByStepRequiredItemId_Result>("Condtion_GetByStepRequiredItemId", stepRequiredItemIdParameter);
        }
    
        public virtual ObjectResult<lkup_StepType_GetAllData_Result> lkup_StepType_GetAllData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lkup_StepType_GetAllData_Result>("lkup_StepType_GetAllData");
        }
    
        public virtual ObjectResult<Object_StepRequiredItem_GetbyObjectId_Result> Object_StepRequiredItem_GetbyObjectId(Nullable<System.Guid> objectId, Nullable<System.Guid> objectTypeId)
        {
            var objectIdParameter = objectId.HasValue ?
                new ObjectParameter("ObjectId", objectId) :
                new ObjectParameter("ObjectId", typeof(System.Guid));
    
            var objectTypeIdParameter = objectTypeId.HasValue ?
                new ObjectParameter("ObjectTypeId", objectTypeId) :
                new ObjectParameter("ObjectTypeId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Object_StepRequiredItem_GetbyObjectId_Result>("Object_StepRequiredItem_GetbyObjectId", objectIdParameter, objectTypeIdParameter);
        }
    
        public virtual ObjectResult<TM_GetCFInfo_Result> TM_GetCFInfo(Nullable<System.Guid> cFId)
        {
            var cFIdParameter = cFId.HasValue ?
                new ObjectParameter("CFId", cFId) :
                new ObjectParameter("CFId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TM_GetCFInfo_Result>("TM_GetCFInfo", cFIdParameter);
        }
    
        public virtual ObjectResult<TM_GetCustomFieldValue_Result> TM_GetCustomFieldValue(Nullable<System.Guid> cFId, Nullable<System.Guid> objectId)
        {
            var cFIdParameter = cFId.HasValue ?
                new ObjectParameter("cFId", cFId) :
                new ObjectParameter("cFId", typeof(System.Guid));
    
            var objectIdParameter = objectId.HasValue ?
                new ObjectParameter("objectId", objectId) :
                new ObjectParameter("objectId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TM_GetCustomFieldValue_Result>("TM_GetCustomFieldValue", cFIdParameter, objectIdParameter);
        }
    
        public virtual ObjectResult<TM_GetListValues_Result> TM_GetListValues(Nullable<System.Guid> lookUpListId)
        {
            var lookUpListIdParameter = lookUpListId.HasValue ?
                new ObjectParameter("LookUpListId", lookUpListId) :
                new ObjectParameter("LookUpListId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TM_GetListValues_Result>("TM_GetListValues", lookUpListIdParameter);
        }
    
        public virtual ObjectResult<ObjectTypeWorkflow_GetWFInfoByObjectTypeId_Result> ObjectTypeWorkflow_GetWFInfoByObjectTypeId(Nullable<System.Guid> objectTypeId)
        {
            var objectTypeIdParameter = objectTypeId.HasValue ?
                new ObjectParameter("ObjectTypeId", objectTypeId) :
                new ObjectParameter("ObjectTypeId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObjectTypeWorkflow_GetWFInfoByObjectTypeId_Result>("ObjectTypeWorkflow_GetWFInfoByObjectTypeId", objectTypeIdParameter);
        }
    
        public virtual ObjectResult<TM_GetWFStepRequiredItems_Result> TM_GetWFStepRequiredItems(Nullable<System.Guid> stepId, Nullable<System.Guid> requiredItemTypeId)
        {
            var stepIdParameter = stepId.HasValue ?
                new ObjectParameter("StepId", stepId) :
                new ObjectParameter("StepId", typeof(System.Guid));
    
            var requiredItemTypeIdParameter = requiredItemTypeId.HasValue ?
                new ObjectParameter("RequiredItemTypeId", requiredItemTypeId) :
                new ObjectParameter("RequiredItemTypeId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TM_GetWFStepRequiredItems_Result>("TM_GetWFStepRequiredItems", stepIdParameter, requiredItemTypeIdParameter);
        }
    
        public virtual ObjectResult<TM_StepRequiredItem_GetbyObjectId_Result> TM_StepRequiredItem_GetbyObjectId(Nullable<System.Guid> objectId)
        {
            var objectIdParameter = objectId.HasValue ?
                new ObjectParameter("ObjectId", objectId) :
                new ObjectParameter("ObjectId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TM_StepRequiredItem_GetbyObjectId_Result>("TM_StepRequiredItem_GetbyObjectId", objectIdParameter);
        }
    
        public virtual ObjectResult<Step_GetByWorkflowId_Result> Step_GetByWorkflowId(Nullable<System.Guid> workflowId)
        {
            var workflowIdParameter = workflowId.HasValue ?
                new ObjectParameter("WorkflowId", workflowId) :
                new ObjectParameter("WorkflowId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Step_GetByWorkflowId_Result>("Step_GetByWorkflowId", workflowIdParameter);
        }
    }
}
