//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class ObjectStepHistory
    {
    	
    
        public ObjectStepHistory()
        {
            this.StepCompletedItemHistory = new HashSet<StepCompletedItemHistory>();
        }
    
    
        [DataMember] public System.Guid ID { get; set; }
    
        [DataMember] public string ObjectId { get; set; }
    
        [DataMember] public System.Guid StepId { get; set; }
    
        [DataMember] public System.Guid WorkflowId { get; set; }
    
        [DataMember] public Nullable<System.DateTime> StartDate { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CompletionDate { get; set; }
    
        [DataMember] public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> StatusId { get; set; }
    
        [DataMember] public Nullable<System.Guid> OriginalOwnerId { get; set; }
    
        [DataMember] public Nullable<System.Guid> ActorId { get; set; }
    
        [DataMember] public Nullable<bool> IsCompleted { get; set; }
    
        [DataMember] public Nullable<bool> ActorIsDelegate { get; set; }
    
        [DataMember] public Nullable<int> FinishVariance { get; set; }
    
        [DataMember] public string Comments { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public Nullable<bool> IsActive { get; set; }
    
        public virtual Step Step { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<StepCompletedItemHistory> StepCompletedItemHistory { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
