//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Object_Step_StepRequiredItem
    {
    	
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public Nullable<System.Guid> Step_StepRequiredItemId { get; set; }
    
        [DataMember] public Nullable<System.Guid> ObjectId { get; set; }
    
        [DataMember] public string Url { get; set; }
    
        [DataMember] public Nullable<System.Guid> AttchamentId { get; set; }
    
        [DataMember] public string Text_Value { get; set; }
    
        [DataMember] public string NText_Value { get; set; }
    
        [DataMember] public Nullable<double> Number_Value { get; set; }
    
        [DataMember] public Nullable<System.Guid> LookupListValueId { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual lkup_LookUpListValue lkup_LookUpListValue { get; set; }
        public virtual Step_StepRequiredItem Step_StepRequiredItem { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
