//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class SecurityMatrix
    {
    	
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public System.Guid ObjectId { get; set; }
    
        [DataMember] public System.Guid SecurityRoleId { get; set; }
    
        [DataMember] public Nullable<System.Guid> UserId { get; set; }
    
        [DataMember] public Nullable<System.Guid> GroupId { get; set; }
    
        [DataMember] public string Notes { get; set; }
    
        [DataMember] public bool Active { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        public virtual lkup_Group lkup_Group { get; set; }
        public virtual lkup_SecurityRole lkup_SecurityRole { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
