//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class StepType_Status
    {
    	
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public Nullable<System.Guid> StepTypeId { get; set; }
    
        [DataMember] public Nullable<System.Guid> StatusId { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModificationDate { get; set; }
    
        [DataMember] public Nullable<System.DateTime> IsActive { get; set; }
    
        public virtual lkup_Status lkup_Status { get; set; }
        public virtual lkup_StepType lkup_StepType { get; set; }
    }
}
