//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Step
    {
    	
    
        public Step()
        {
            this.FlowLogic = new HashSet<FlowLogic>();
            this.FlowLogic1 = new HashSet<FlowLogic>();
            this.ObjectStepHistory = new HashSet<ObjectStepHistory>();
            this.Step1 = new HashSet<Step>();
            this.Step_StepRequiredItem = new HashSet<Step_StepRequiredItem>();
            this.WorkflowComment = new HashSet<WorkflowComment>();
            this.WorkflowDelegation = new HashSet<WorkflowDelegation>();
        }
    
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public string Name { get; set; }
    
        [DataMember] public string Description { get; set; }
    
        [DataMember] public Nullable<System.Guid> WorkflowId { get; set; }
    
        [DataMember] public Nullable<System.Guid> PhaseId { get; set; }
    
        [DataMember] public Nullable<System.Guid> StepTypeId { get; set; }
    
        [DataMember] public Nullable<System.Guid> ParentId { get; set; }
    
        [DataMember] public string Numbering { get; set; }
    
        [DataMember] public Nullable<int> Order { get; set; }
    
        [DataMember] public Nullable<System.Guid> SecurityRoleId { get; set; }
    
        [DataMember] public Nullable<int> TimeOutDuration { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        public virtual ICollection<FlowLogic> FlowLogic { get; set; }
        public virtual ICollection<FlowLogic> FlowLogic1 { get; set; }
        public virtual lkup_Phase lkup_Phase { get; set; }
        public virtual lkup_SecurityRole lkup_SecurityRole { get; set; }
        public virtual lkup_StepType lkup_StepType { get; set; }
        public virtual ICollection<ObjectStepHistory> ObjectStepHistory { get; set; }
        public virtual ICollection<Step> Step1 { get; set; }
        public virtual Step Step2 { get; set; }
        public virtual ICollection<Step_StepRequiredItem> Step_StepRequiredItem { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<WorkflowComment> WorkflowComment { get; set; }
        public virtual ICollection<WorkflowDelegation> WorkflowDelegation { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
