//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class User
    {
    	
    
        public User()
        {
            this.Action_SecurityRole_MailTemplate = new HashSet<Action_SecurityRole_MailTemplate>();
            this.Action_SecurityRole_MailTemplate1 = new HashSet<Action_SecurityRole_MailTemplate>();
            this.Action_Step_MailTemplate = new HashSet<Action_Step_MailTemplate>();
            this.Action_Step_MailTemplate1 = new HashSet<Action_Step_MailTemplate>();
            this.ActionsNotification = new HashSet<ActionsNotification>();
            this.ActionsNotification1 = new HashSet<ActionsNotification>();
            this.Attachment = new HashSet<Attachment>();
            this.Attachment1 = new HashSet<Attachment>();
            this.Condtion = new HashSet<Condtion>();
            this.Condtion1 = new HashSet<Condtion>();
            this.CustomFieldType = new HashSet<CustomFieldType>();
            this.CustomFieldType1 = new HashSet<CustomFieldType>();
            this.DelegationScope = new HashSet<DelegationScope>();
            this.DelegationScope1 = new HashSet<DelegationScope>();
            this.FlowLogic = new HashSet<FlowLogic>();
            this.FlowLogic1 = new HashSet<FlowLogic>();
            this.FlowLogic_Condtion = new HashSet<FlowLogic_Condtion>();
            this.FlowLogic_Condtion1 = new HashSet<FlowLogic_Condtion>();
            this.FlowLogicRequiredItem = new HashSet<FlowLogicRequiredItem>();
            this.FlowLogicRequiredItem1 = new HashSet<FlowLogicRequiredItem>();
            this.ItemSubmittionHistory = new HashSet<ItemSubmittionHistory>();
            this.ItemSubmittionHistory1 = new HashSet<ItemSubmittionHistory>();
            this.lkup_DelegationStatus = new HashSet<lkup_DelegationStatus>();
            this.lkup_DelegationStatus1 = new HashSet<lkup_DelegationStatus>();
            this.lkup_Group = new HashSet<lkup_Group>();
            this.lkup_Group1 = new HashSet<lkup_Group>();
            this.lkup_JobTitle = new HashSet<lkup_JobTitle>();
            this.lkup_JobTitle1 = new HashSet<lkup_JobTitle>();
            this.lkup_Language = new HashSet<lkup_Language>();
            this.lkup_Language1 = new HashSet<lkup_Language>();
            this.lkup_LookupList = new HashSet<lkup_LookupList>();
            this.lkup_LookupList1 = new HashSet<lkup_LookupList>();
            this.lkup_LookUpListValue = new HashSet<lkup_LookUpListValue>();
            this.lkup_LookUpListValue1 = new HashSet<lkup_LookUpListValue>();
            this.lkup_MailTemplate = new HashSet<lkup_MailTemplate>();
            this.lkup_MailTemplate1 = new HashSet<lkup_MailTemplate>();
            this.lkup_MatchingCritria = new HashSet<lkup_MatchingCritria>();
            this.lkup_MatchingCritria1 = new HashSet<lkup_MatchingCritria>();
            this.lkup_Path = new HashSet<lkup_Path>();
            this.lkup_Path1 = new HashSet<lkup_Path>();
            this.lkup_Phase = new HashSet<lkup_Phase>();
            this.lkup_Phase1 = new HashSet<lkup_Phase>();
            this.lkup_RequiredItemType = new HashSet<lkup_RequiredItemType>();
            this.lkup_RequiredItemType1 = new HashSet<lkup_RequiredItemType>();
            this.lkup_SecurityRole = new HashSet<lkup_SecurityRole>();
            this.lkup_SecurityRole1 = new HashSet<lkup_SecurityRole>();
            this.lkup_Status = new HashSet<lkup_Status>();
            this.lkup_Status1 = new HashSet<lkup_Status>();
            this.lkup_StepType = new HashSet<lkup_StepType>();
            this.lkup_StepType1 = new HashSet<lkup_StepType>();
            this.lkup_SubmittionStatus = new HashSet<lkup_SubmittionStatus>();
            this.lkup_SubmittionStatus1 = new HashSet<lkup_SubmittionStatus>();
            this.lkup_TimeOutStatus = new HashSet<lkup_TimeOutStatus>();
            this.lkup_TimeOutStatus1 = new HashSet<lkup_TimeOutStatus>();
            this.Object_StepRequiredItem = new HashSet<Object_StepRequiredItem>();
            this.Object_StepRequiredItem1 = new HashSet<Object_StepRequiredItem>();
            this.ObjectInstanceData = new HashSet<ObjectInstanceData>();
            this.ObjectInstanceData1 = new HashSet<ObjectInstanceData>();
            this.ObjectInstanceData_CurrentSteps = new HashSet<ObjectInstanceData_CurrentSteps>();
            this.ObjectInstanceData_CurrentSteps1 = new HashSet<ObjectInstanceData_CurrentSteps>();
            this.ObjectStepHistory = new HashSet<ObjectStepHistory>();
            this.ObjectStepHistory1 = new HashSet<ObjectStepHistory>();
            this.ObjectTypeWorkflow = new HashSet<ObjectTypeWorkflow>();
            this.ObjectTypeWorkflow1 = new HashSet<ObjectTypeWorkflow>();
            this.SecurityMatrix = new HashSet<SecurityMatrix>();
            this.SecurityMatrix1 = new HashSet<SecurityMatrix>();
            this.Step = new HashSet<Step>();
            this.Step1 = new HashSet<Step>();
            this.Step_StepRequiredItem = new HashSet<Step_StepRequiredItem>();
            this.Step_StepRequiredItem1 = new HashSet<Step_StepRequiredItem>();
            this.StepCompletedItemHistory = new HashSet<StepCompletedItemHistory>();
            this.StepCompletedItemHistory1 = new HashSet<StepCompletedItemHistory>();
            this.StepRequiredItem = new HashSet<StepRequiredItem>();
            this.StepRequiredItem1 = new HashSet<StepRequiredItem>();
            this.Workflow_Attachment = new HashSet<Workflow_Attachment>();
            this.Workflow_Attachment1 = new HashSet<Workflow_Attachment>();
            this.User1 = new HashSet<User>();
            this.Workflow = new HashSet<Workflow>();
            this.Workflow1 = new HashSet<Workflow>();
            this.WorkflowComment = new HashSet<WorkflowComment>();
            this.WorkflowComment1 = new HashSet<WorkflowComment>();
            this.WorkflowDelegation = new HashSet<WorkflowDelegation>();
            this.WorkflowDelegation1 = new HashSet<WorkflowDelegation>();
            this.WorkflowDelegation2 = new HashSet<WorkflowDelegation>();
            this.WorkflowDelegation3 = new HashSet<WorkflowDelegation>();
        }
    
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public string FirstName { get; set; }
    
        [DataMember] public string LastName { get; set; }
    
        [DataMember] public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        [DataMember] public Nullable<bool> IsAD { get; set; }
    
        [DataMember] public string Username { get; set; }
    
        [DataMember] public string Password { get; set; }
    
        [DataMember] public Nullable<System.Guid> GroupId { get; set; }
    
        [DataMember] public string Email { get; set; }
    
        [DataMember] public Nullable<System.Guid> ParentId { get; set; }
    
        [DataMember] public Nullable<System.Guid> JobTitleId { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        public virtual ICollection<Action_SecurityRole_MailTemplate> Action_SecurityRole_MailTemplate { get; set; }
        public virtual ICollection<Action_SecurityRole_MailTemplate> Action_SecurityRole_MailTemplate1 { get; set; }
        public virtual ICollection<Action_Step_MailTemplate> Action_Step_MailTemplate { get; set; }
        public virtual ICollection<Action_Step_MailTemplate> Action_Step_MailTemplate1 { get; set; }
        public virtual ICollection<ActionsNotification> ActionsNotification { get; set; }
        public virtual ICollection<ActionsNotification> ActionsNotification1 { get; set; }
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual ICollection<Attachment> Attachment1 { get; set; }
        public virtual ICollection<Condtion> Condtion { get; set; }
        public virtual ICollection<Condtion> Condtion1 { get; set; }
        public virtual ICollection<CustomFieldType> CustomFieldType { get; set; }
        public virtual ICollection<CustomFieldType> CustomFieldType1 { get; set; }
        public virtual ICollection<DelegationScope> DelegationScope { get; set; }
        public virtual ICollection<DelegationScope> DelegationScope1 { get; set; }
        public virtual ICollection<FlowLogic> FlowLogic { get; set; }
        public virtual ICollection<FlowLogic> FlowLogic1 { get; set; }
        public virtual ICollection<FlowLogic_Condtion> FlowLogic_Condtion { get; set; }
        public virtual ICollection<FlowLogic_Condtion> FlowLogic_Condtion1 { get; set; }
        public virtual ICollection<FlowLogicRequiredItem> FlowLogicRequiredItem { get; set; }
        public virtual ICollection<FlowLogicRequiredItem> FlowLogicRequiredItem1 { get; set; }
        public virtual ICollection<ItemSubmittionHistory> ItemSubmittionHistory { get; set; }
        public virtual ICollection<ItemSubmittionHistory> ItemSubmittionHistory1 { get; set; }
        public virtual ICollection<lkup_DelegationStatus> lkup_DelegationStatus { get; set; }
        public virtual ICollection<lkup_DelegationStatus> lkup_DelegationStatus1 { get; set; }
        public virtual ICollection<lkup_Group> lkup_Group { get; set; }
        public virtual ICollection<lkup_Group> lkup_Group1 { get; set; }
        public virtual lkup_Group lkup_Group2 { get; set; }
        public virtual ICollection<lkup_JobTitle> lkup_JobTitle { get; set; }
        public virtual ICollection<lkup_JobTitle> lkup_JobTitle1 { get; set; }
        public virtual lkup_JobTitle lkup_JobTitle2 { get; set; }
        public virtual ICollection<lkup_Language> lkup_Language { get; set; }
        public virtual ICollection<lkup_Language> lkup_Language1 { get; set; }
        public virtual ICollection<lkup_LookupList> lkup_LookupList { get; set; }
        public virtual ICollection<lkup_LookupList> lkup_LookupList1 { get; set; }
        public virtual ICollection<lkup_LookUpListValue> lkup_LookUpListValue { get; set; }
        public virtual ICollection<lkup_LookUpListValue> lkup_LookUpListValue1 { get; set; }
        public virtual ICollection<lkup_MailTemplate> lkup_MailTemplate { get; set; }
        public virtual ICollection<lkup_MailTemplate> lkup_MailTemplate1 { get; set; }
        public virtual ICollection<lkup_MatchingCritria> lkup_MatchingCritria { get; set; }
        public virtual ICollection<lkup_MatchingCritria> lkup_MatchingCritria1 { get; set; }
        public virtual ICollection<lkup_Path> lkup_Path { get; set; }
        public virtual ICollection<lkup_Path> lkup_Path1 { get; set; }
        public virtual ICollection<lkup_Phase> lkup_Phase { get; set; }
        public virtual ICollection<lkup_Phase> lkup_Phase1 { get; set; }
        public virtual ICollection<lkup_RequiredItemType> lkup_RequiredItemType { get; set; }
        public virtual ICollection<lkup_RequiredItemType> lkup_RequiredItemType1 { get; set; }
        public virtual ICollection<lkup_SecurityRole> lkup_SecurityRole { get; set; }
        public virtual ICollection<lkup_SecurityRole> lkup_SecurityRole1 { get; set; }
        public virtual ICollection<lkup_Status> lkup_Status { get; set; }
        public virtual ICollection<lkup_Status> lkup_Status1 { get; set; }
        public virtual ICollection<lkup_StepType> lkup_StepType { get; set; }
        public virtual ICollection<lkup_StepType> lkup_StepType1 { get; set; }
        public virtual ICollection<lkup_SubmittionStatus> lkup_SubmittionStatus { get; set; }
        public virtual ICollection<lkup_SubmittionStatus> lkup_SubmittionStatus1 { get; set; }
        public virtual ICollection<lkup_TimeOutStatus> lkup_TimeOutStatus { get; set; }
        public virtual ICollection<lkup_TimeOutStatus> lkup_TimeOutStatus1 { get; set; }
        public virtual ICollection<Object_StepRequiredItem> Object_StepRequiredItem { get; set; }
        public virtual ICollection<Object_StepRequiredItem> Object_StepRequiredItem1 { get; set; }
        public virtual ICollection<ObjectInstanceData> ObjectInstanceData { get; set; }
        public virtual ICollection<ObjectInstanceData> ObjectInstanceData1 { get; set; }
        public virtual ICollection<ObjectInstanceData_CurrentSteps> ObjectInstanceData_CurrentSteps { get; set; }
        public virtual ICollection<ObjectInstanceData_CurrentSteps> ObjectInstanceData_CurrentSteps1 { get; set; }
        public virtual ICollection<ObjectStepHistory> ObjectStepHistory { get; set; }
        public virtual ICollection<ObjectStepHistory> ObjectStepHistory1 { get; set; }
        public virtual ICollection<ObjectTypeWorkflow> ObjectTypeWorkflow { get; set; }
        public virtual ICollection<ObjectTypeWorkflow> ObjectTypeWorkflow1 { get; set; }
        public virtual ObjectTypeWorkflow ObjectTypeWorkflow2 { get; set; }
        public virtual ICollection<SecurityMatrix> SecurityMatrix { get; set; }
        public virtual ICollection<SecurityMatrix> SecurityMatrix1 { get; set; }
        public virtual ICollection<Step> Step { get; set; }
        public virtual ICollection<Step> Step1 { get; set; }
        public virtual ICollection<Step_StepRequiredItem> Step_StepRequiredItem { get; set; }
        public virtual ICollection<Step_StepRequiredItem> Step_StepRequiredItem1 { get; set; }
        public virtual ICollection<StepCompletedItemHistory> StepCompletedItemHistory { get; set; }
        public virtual ICollection<StepCompletedItemHistory> StepCompletedItemHistory1 { get; set; }
        public virtual ICollection<StepRequiredItem> StepRequiredItem { get; set; }
        public virtual ICollection<StepRequiredItem> StepRequiredItem1 { get; set; }
        public virtual ICollection<Workflow_Attachment> Workflow_Attachment { get; set; }
        public virtual ICollection<Workflow_Attachment> Workflow_Attachment1 { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<Workflow> Workflow { get; set; }
        public virtual ICollection<Workflow> Workflow1 { get; set; }
        public virtual ICollection<WorkflowComment> WorkflowComment { get; set; }
        public virtual ICollection<WorkflowComment> WorkflowComment1 { get; set; }
        public virtual ICollection<WorkflowDelegation> WorkflowDelegation { get; set; }
        public virtual ICollection<WorkflowDelegation> WorkflowDelegation1 { get; set; }
        public virtual ICollection<WorkflowDelegation> WorkflowDelegation2 { get; set; }
        public virtual ICollection<WorkflowDelegation> WorkflowDelegation3 { get; set; }
    }
}
