//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Workflow
    {
    	
    
        public Workflow()
        {
            this.lkup_Phase = new HashSet<lkup_Phase>();
            this.ObjectInstanceData = new HashSet<ObjectInstanceData>();
            this.ObjectStepHistory = new HashSet<ObjectStepHistory>();
            this.Step = new HashSet<Step>();
            this.Workflow_Attachment = new HashSet<Workflow_Attachment>();
            this.WorkflowComment = new HashSet<WorkflowComment>();
            this.WorkflowDelegation = new HashSet<WorkflowDelegation>();
        }
    
    
        [DataMember] public System.Guid Id { get; set; }
    
        [DataMember] public string Name { get; set; }
    
        [DataMember] public string Title { get; set; }
    
        [DataMember] public string Description { get; set; }
    
        [DataMember] public Nullable<System.Guid> LanguageId { get; set; }
    
        [DataMember] public Nullable<bool> DisableUpcomingForms { get; set; }
    
        [DataMember] public Nullable<System.Guid> CreatedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> CreationDate { get; set; }
    
        [DataMember] public Nullable<System.Guid> ModifiedBy { get; set; }
    
        [DataMember] public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [DataMember] public bool IsActive { get; set; }
    
        public virtual ICollection<lkup_Phase> lkup_Phase { get; set; }
        public virtual ICollection<ObjectInstanceData> ObjectInstanceData { get; set; }
        public virtual ICollection<ObjectStepHistory> ObjectStepHistory { get; set; }
        public virtual ICollection<Step> Step { get; set; }
        public virtual ICollection<Workflow_Attachment> Workflow_Attachment { get; set; }
        public virtual ICollection<WorkflowComment> WorkflowComment { get; set; }
        public virtual ICollection<WorkflowDelegation> WorkflowDelegation { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
